#!/usr/bin/env bash
# used for rsyncing to a build server

if [ "$1" == "" ]; then
    echo 'You need to provide a build server';
    exit 1;
fi

case "$OSTYPE" in
  solaris*) OS="SOLARIS" ;;
  darwin*)  OS="OSX" ;;
  linux*)   OS="LINUX" ;;
  bsd*)     OS="BSD" ;;
esac

function send() {
    rsync -r . $1 --progress
}

send $1;

if [ "$OS" == 'LINUX' ]; then
    while inotifywait --exclude '\..*sw.' -r -q -e modify ./; do
        send $1;
    done
elif [ "$OS" == 'OSX' ]; then
    while fswatch --one-event src/ tasks/; do
        send $1;
    done
fi
